/**
 * ExportButton.tsx — One-click Markdown export of the analysis result.
 * Downloads a .md file with the full structured report.
 */

import type { AnalysisResult } from '../api/analyze';

interface ExportButtonProps {
  result: AnalysisResult;
}

const TYPE_EMOJI: Record<string, string> = {
  bug_storm:     '🔴',
  refactor:      '🟡',
  pivot:         '🟢',
  feature_burst: '🔵',
  stability:     '⚪',
};

function generateMarkdown(result: AnalysisResult): string {
  const { metadata, summary, milestones, metrics, churn_summary, data_quality } = result;

  const lines: string[] = [
    `# CodeDNA Analysis Report`,
    ``,
    `> Generated by CodeDNA — AI Codebase Archaeologist (Gemma 4)`,
    ``,
    `## Overview`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Commits Analyzed | ${metadata.commits_analyzed} |`,
    `| Time Span | ${metadata.time_span_readable} |`,
    `| Health Score | **${metadata.health_score} / 100** |`,
    `| Data Quality | ${data_quality} |`,
    ``,
    `**Health Justification:** ${metadata.health_justification}`,
    ``,
    `## Summary`,
    ``,
    summary,
    ``,
    `## Milestones`,
    ``,
    ...milestones.map((m) => [
      `### ${TYPE_EMOJI[m.type] ?? ''} ${m.title}`,
      ``,
      `- **Period:** ${m.period}`,
      `- **Type:** ${m.type}`,
      `- **Severity:** ${m.severity}`,
      ``,
      m.description,
      ``,
      m.commit_hashes.length > 0
        ? `**Key commits:** ${m.commit_hashes.map((h) => `\`${h.slice(0, 7)}\``).join(', ')}`
        : '',
      ``,
    ].join('\n')),
    `## Metrics`,
    ``,
    `| | |`,
    `|--|--|`,
    `| Most Chaotic Period | ${metrics.most_chaotic_period} |`,
    `| Most Stable Period | ${metrics.most_stable_period} |`,
    `| Biggest Pivot | ${metrics.biggest_pivot_commit ?? 'N/A'} |`,
    `| Bug Fix Ratio | ${metrics.bug_fix_ratio} |`,
    ``,
    `## Churn Summary`,
    ``,
    churn_summary,
    ``,
    `---`,
    `*Powered by [CodeDNA](https://github.com/your-handle/codedna) + Gemma 4*`,
  ];

  return lines.join('\n');
}

export default function ExportButton({ result }: ExportButtonProps) {
  const handleExport = () => {
    const md = generateMarkdown(result);
    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `codedna-report-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <button
      id="btn-export"
      onClick={handleExport}
      className="flex items-center gap-2 px-4 py-2 text-sm font-medium
                 border border-zinc-700 hover:border-zinc-500 text-zinc-400 hover:text-zinc-200
                 rounded-lg transition-all duration-200 active:scale-95
                 focus:outline-none focus:ring-2 focus:ring-zinc-600"
    >
      <span>⬇</span>
      Export Markdown
    </button>
  );
}
