/**
 * ExportButton.tsx — One-click Markdown export of the analysis result.
 * v2: fixed GitHub handle placeholder, added breakdown and new metrics to export.
 */

import type { AnalysisResult } from '../api/analyze';

interface ExportButtonProps {
  result: AnalysisResult;
}

const TYPE_EMOJI: Record<string, string> = {
  bug_storm:     '🔴',
  refactor:      '🟡',
  pivot:         '🟢',
  feature_burst: '🔵',
  stability:     '⚪',
};

function generateMarkdown(result: AnalysisResult): string {
  const { metadata, summary, milestones, metrics, churn_summary, data_quality } = result;

  const breakdownMd =
    metadata.health_breakdown.length > 0
      ? [
          '',
          '### Health Score Breakdown',
          '',
          '| Factor | Delta | Evidence |',
          '|--------|-------|----------|',
          ...metadata.health_breakdown.map(
            (b) => `| ${b.factor} | ${b.delta > 0 ? `+${b.delta}` : b.delta} | ${b.reason} |`,
          ),
          '',
          `**Final score: ${metadata.health_score} / 100** (base: 50)`,
        ]
      : [];

  const lines: string[] = [
    `# CodeDNA Analysis Report`,
    ``,
    `> Generated by [CodeDNA](https://github.com/acchasujal/codedna) — AI Codebase Archaeologist (Gemma 4)`,
    ``,
    `## Overview`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Commits Analyzed | ${metadata.commits_analyzed} |`,
    `| Time Span | ${metadata.time_span_readable} |`,
    `| Health Score | **${metadata.health_score} / 100** |`,
    `| Data Quality | ${data_quality} |`,
    ``,
    `**Health Justification:** ${metadata.health_justification}`,
    ...breakdownMd,
    ``,
    `## Summary`,
    ``,
    summary,
    ``,
    `## Milestones`,
    ``,
    ...milestones.map((m) =>
      [
        `### ${TYPE_EMOJI[m.type] ?? ''} ${m.title}`,
        ``,
        `- **Period:** ${m.period}`,
        `- **Type:** ${m.type}`,
        `- **Severity:** ${m.severity}`,
        `- **Confidence:** ${m.confidence}`,
        m.commit_count != null ? `- **Commits:** ${m.commit_count}` : '',
        m.dominant_files.length > 0
          ? `- **Key Files:** ${m.dominant_files.map((f) => `\`${f}\``).join(', ')}`
          : '',
        ``,
        m.description,
        ``,
        m.commit_hashes.length > 0
          ? `**Key commits:** ${m.commit_hashes.map((h) => `\`${h.slice(0, 7)}\``).join(', ')}`
          : '',
        ``,
      ]
        .filter((l) => l !== undefined)
        .join('\n'),
    ),
    `## Metrics`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Most Chaotic Period | ${metrics.most_chaotic_period} |`,
    `| Most Stable Period | ${metrics.most_stable_period} |`,
    `| Biggest Pivot Commit | ${metrics.biggest_pivot_commit ?? 'N/A'} |`,
    `| Bug Fix Ratio | ${metrics.bug_fix_ratio} |`,
    metrics.peak_month_commits != null
      ? `| Peak Month Commits | ${metrics.peak_month_commits} |`
      : '',
    metrics.avg_monthly_commits != null
      ? `| Avg Monthly Commits | ${metrics.avg_monthly_commits.toFixed(1)} |`
      : '',
    ``,
    `## Churn Summary`,
    ``,
    churn_summary,
    ``,
    `---`,
    `*Powered by [CodeDNA](https://github.com/acchasujal/codedna) + Gemma 4 · Google Gemma 4 Challenge*`,
  ].filter((l) => l !== undefined);

  return lines.join('\n');
}

export default function ExportButton({ result }: ExportButtonProps) {
  const handleExport = () => {
    const md   = generateMarkdown(result);
    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = `codedna-report-${new Date().toISOString().slice(0, 10)}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <button
      id="btn-export"
      onClick={handleExport}
      className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-mono
                 border border-zinc-700 hover:border-zinc-500
                 text-zinc-400 hover:text-zinc-200 rounded-lg
                 transition-colors duration-200 active:scale-95
                 focus:outline-none focus:ring-1 focus:ring-zinc-600"
    >
      <span>↓</span>
      Export MD
    </button>
  );
}
